name: Publish on NPM

on:
  push:
    paths:
      - '.github/workflows/npm_publish.yml'
      - 'package.json'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Installing NPM deps
        run: npm i

      - name: Build
        run: npm run package --production

      - name: Publish on NPM
        run: |
          cd package
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
